[workspace]
resolver = "2"
members = [
    "crates/qbx_lua_syntax",
    "crates/qbx_lua_fmt",
    "crates/qbx_lua_analysis",
    "crates/qbx_fivem_data",
    "crates/qbx_lint",
    "xtask",
]
default-members = [
    "crates/qbx_lua_syntax",
    "crates/qbx_lua_fmt",
    "crates/qbx_lua_analysis",
    "crates/qbx_fivem_data",
    "crates/qbx_lint",
]

[workspace.package]
version = "1.0.3"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/Qbox-project/qbx-lint"

[workspace.dependencies]
qbx_lua_syntax = { version = "=1.0.3", path = "crates/qbx_lua_syntax" }
qbx_lua_fmt = { version = "=1.0.3", path = "crates/qbx_lua_fmt" }
qbx_lua_analysis = { version = "=1.0.3", path = "crates/qbx_lua_analysis" }
qbx_fivem_data = { version = "=1.0.3", path = "crates/qbx_fivem_data" }
smol_str = "0.3"
rustc-hash = "2"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
