---@meta
-- Generated by scripts/generate-glm-stub.mjs from the registration tables of the CfxLua GLM binding
-- (https://raw.githubusercontent.com/citizenfx/lua/luaglm-dev/cfx/libs/glm-binding).
-- Functions without a description are registered by the runtime but not described here; they
-- follow the GLM function of the same name.

---A matrix of 2 to 4 columns and rows.
---@class matrix

---@alias glm.vec vector2|vector3|vector4
---@alias glm.num number|vector2|vector3|vector4

---GLM mathematics for vectors, quaternions and matrices, built into CfxLua.
---@class glm
glm = {}

---@type number
glm.cos_one_over_two = 0

---@type number
glm.e = 0

---@type number
glm.eps = 0

---@type number
glm.epsilon = 0

---@type number
glm.euler = 0

---@type number
glm.feps = 0

---@type number
glm.four_over_pi = 0

---@type number
glm.FP_INFINITE = 0

---@type number
glm.FP_NAN = 0

---@type number
glm.FP_NORMAL = 0

---@type number
glm.FP_SUBNORMAL = 0

---@type number
glm.FP_ZERO = 0

---@type number
glm.golden_ratio = 0

---@type number
glm.half_pi = 0

---@type number
glm.huge = 0

---@type number
glm.ln_ln_two = 0

---@type number
glm.ln_ten = 0

---@type number
glm.ln_two = 0

---@type number
glm.maxinteger = 0

---@type number
glm.mininteger = 0

---@type number
glm.one = 0

---@type number
glm.one_over_pi = 0

---@type number
glm.one_over_root_two = 0

---@type number
glm.one_over_two_pi = 0

---@type number
glm.pi = 0

---@type number
glm.quarter_pi = 0

---@type number
glm.root_five = 0

---@type number
glm.root_half_pi = 0

---@type number
glm.root_ln_four = 0

---@type number
glm.root_pi = 0

---@type number
glm.root_three = 0

---@type number
glm.root_two = 0

---@type number
glm.root_two_pi = 0

---@type number
glm.third = 0

---@type number
glm.three_over_two_pi = 0

---@type number
glm.two_over_pi = 0

---@type number
glm.two_over_root_pi = 0

---@type number
glm.two_pi = 0

---@type number
glm.two_thirds = 0

---@type number
glm.zero = 0

---Absolute value, per component.
---@param x glm.num
---@return glm.num
function glm.abs(x) end

---Arc cosine in radians, per component.
---@param x glm.num
---@return glm.num
function glm.acos(x) end

---@param ... any
---@return any
function glm.acosh(...) end

---@param ... any
---@return any
function glm.acot(...) end

---@param ... any
---@return any
function glm.acoth(...) end

---@param ... any
---@return any
function glm.acsc(...) end

---@param ... any
---@return any
function glm.acsch(...) end

---@param ... any
---@return any
function glm.adjugate(...) end

---@param ... any
---@return any
function glm.affineInverse(...) end

---True when every component is truthy.
---@param v any
---@return boolean
function glm.all(v) end

---@param ... any
---@return any
function glm.allEqual(...) end

---Angle in radians between two normalized vectors, or the rotation angle of a quaternion.
---@param x glm.vec|quat
---@param y? glm.vec
---@return number
function glm.angle(x, y) end

---Alias of `glm.angle`. Angle in radians between two normalized vectors, or the rotation angle of a quaternion.
---@param x glm.vec|quat
---@param y? glm.vec
---@return number
function glm.angle_to(x, y) end

---Quaternion that rotates by `angle` radians around `axis`.
---@param angle number
---@param axis vector3
---@return quat
function glm.angleAxis(angle, axis) end

---True when at least one component is truthy.
---@param v any
---@return boolean
function glm.any(v) end

---@param ... any
---@return any
function glm.anyNotEqual(...) end

---Alias of `glm.epsilonEqual`. Whether `|x - y| < epsilon`, per component.
---@param x glm.num
---@param y glm.num
---@param epsilon glm.num
---@return boolean|glm.vec
function glm.approx(x, y, epsilon) end

---Alias of `glm.epsilonEqual`. Whether `|x - y| < epsilon`, per component.
---@param x glm.num
---@param y glm.num
---@param epsilon glm.num
---@return boolean|glm.vec
function glm.approximately(x, y, epsilon) end

---@param ... any
---@return any
function glm.areCollinear(...) end

---@param ... any
---@return any
function glm.areOrthogonal(...) end

---@param ... any
---@return any
function glm.areOrthonormal(...) end

---@param ... any
---@return any
function glm.asec(...) end

---@param ... any
---@return any
function glm.asech(...) end

---Arc sine in radians, per component.
---@param x glm.num
---@return glm.num
function glm.asin(x) end

---@param ... any
---@return any
function glm.asinh(...) end

---Arc tangent in radians; with two arguments the quadrant follows from the signs of `y` and `x`.
---@param y glm.num
---@param x? glm.num
---@return glm.num
function glm.atan(y, x) end

---Arc tangent of `y / x` in radians, using the signs to pick the quadrant.
---@param y glm.num
---@param x glm.num
---@return glm.num
function glm.atan2(y, x) end

---@param ... any
---@return any
function glm.atanh(...) end

---Rotation axis of a quaternion.
---@param q quat
---@return vector3
function glm.axis(q) end

---@param ... any
---@return any
function glm.axisAngle(...) end

---@param ... any
---@return any
function glm.axisAngleMatrix(...) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.backEaseIn(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.backEaseInOut(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.backEaseOut(t) end

---Random point inside a sphere of the given radius.
---@param radius number
---@return vector3
function glm.ballRand(radius) end

---@param ... any
---@return any
function glm.barycentric(...) end

---@param ... any
---@return any
function glm.basis(...) end

---@param ... any
---@return any
function glm.begin(...) end

---@param ... any
---@return any
function glm.billboard(...) end

---@param ... any
---@return any
function glm.billboardLH(...) end

---@param ... any
---@return any
function glm.billboardRH(...) end

---@param ... any
---@return any
function glm.bitCount(...) end

---@param ... any
---@return any
function glm.bitfieldDeinterleave(...) end

---@param ... any
---@return any
function glm.bitfieldExtract(...) end

---@param ... any
---@return any
function glm.bitfieldFillOne(...) end

---@param ... any
---@return any
function glm.bitfieldFillZero(...) end

---@param ... any
---@return any
function glm.bitfieldInsert(...) end

---@param ... any
---@return any
function glm.bitfieldInterleave(...) end

---@param ... any
---@return any
function glm.bitfieldReverse(...) end

---@param ... any
---@return any
function glm.bitfieldRotateLeft(...) end

---@param ... any
---@return any
function glm.bitfieldRotateRight(...) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.bounceEaseIn(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.bounceEaseInOut(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.bounceEaseOut(t) end

---@param ... any
---@return any
function glm.bvec(...) end

---@param ... any
---@return any
function glm.bvec1(...) end

---@param ... any
---@return any
function glm.bvec2(...) end

---@param ... any
---@return any
function glm.bvec3(...) end

---@param ... any
---@return any
function glm.bvec4(...) end

---@param ... any
---@return any
function glm.catmullRom(...) end

---@param ... any
---@return any
function glm.cbrt(...) end

---Rounds up, per component.
---@param x glm.num
---@return glm.num
function glm.ceil(x) end

---@param ... any
---@return any
function glm.ceilMultiple(...) end

---@param ... any
---@return any
function glm.ceilPowerOfTwo(...) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.circularEaseIn(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.circularEaseInOut(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.circularEaseOut(t) end

---Random point on a circle of the given radius.
---@param radius number
---@return vector2
function glm.circularRand(radius) end

---Restricts `x` to `minVal..maxVal`; with one argument to 0..1.
---@param x glm.num
---@param minVal? glm.num
---@param maxVal? glm.num
---@return glm.num
function glm.clamp(x, minVal, maxVal) end

---@param ... any
---@return any
function glm.clampLength(...) end

---@param ... any
---@return any
function glm.clampMagnitude(...) end

---@param ... any
---@return any
function glm.closeBounded(...) end

---@param ... any
---@return any
function glm.closestPointOnLine(...) end

---@param ... any
---@return any
function glm.colMajor(...) end

---@param ... any
---@return any
function glm.colMajor2(...) end

---@param ... any
---@return any
function glm.colMajor3(...) end

---@param ... any
---@return any
function glm.colMajor4(...) end

---@param ... any
---@return any
function glm.column(...) end

---@param ... any
---@return any
function glm.compAdd(...) end

---@param ... any
---@return any
function glm.compMax(...) end

---@param ... any
---@return any
function glm.compMin(...) end

---@param ... any
---@return any
function glm.compMul(...) end

---@param ... any
---@return any
function glm.compNormalize(...) end

---@param ... any
---@return any
function glm.components(...) end

---@param ... any
---@return any
function glm.compScale(...) end

---@param ... any
---@return any
function glm.computeCovarianceMatrix(...) end

---Conjugate of a quaternion.
---@param q quat
---@return quat
function glm.conjugate(q) end

---@param ... any
---@return any
function glm.containsProjection(...) end

---@param ... any
---@return any
function glm.convertD65XYZToD50XYZ(...) end

---@param ... any
---@return any
function glm.convertD65XYZToLinearSRGB(...) end

---@param ... any
---@return any
function glm.convertLinearSRGBToD50XYZ(...) end

---@param ... any
---@return any
function glm.convertLinearSRGBToD65XYZ(...) end

---@param ... any
---@return any
function glm.convertLinearToSRGB(...) end

---@param ... any
---@return any
function glm.convertSRGBToLinear(...) end

---@param ... any
---@return any
function glm.copysign(...) end

---Cosine of an angle in radians, per component.
---@param x glm.num
---@return glm.num
function glm.cos(x) end

---Hyperbolic cosine, per component.
---@param x glm.num
---@return glm.num
function glm.cosh(x) end

---@param ... any
---@return any
function glm.cot(...) end

---@param ... any
---@return any
function glm.coth(...) end

---Cross product.
---@param x vector3
---@param y vector3
---@return vector3
function glm.cross(x, y) end

---@param ... any
---@return any
function glm.csc(...) end

---@param ... any
---@return any
function glm.csch(...) end

---@param ... any
---@return any
function glm.cubic(...) end

---@param ... any
---@return any
function glm.cubic_interpolate(...) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.cubicEaseIn(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.cubicEaseInOut(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.cubicEaseOut(t) end

---@param ... any
---@return any
function glm.decompose(...) end

---Alias of `glm.degrees`. Converts radians to degrees, per component.
---@param x glm.num
---@return glm.num
function glm.deg(x) end

---Converts radians to degrees, per component.
---@param x glm.num
---@return glm.num
function glm.degrees(x) end

---@param ... any
---@return any
function glm.deltaAngle(...) end

---@param ... any
---@return any
function glm.derivedEulerAngleX(...) end

---@param ... any
---@return any
function glm.derivedEulerAngleY(...) end

---@param ... any
---@return any
function glm.derivedEulerAngleZ(...) end

---Determinant of a square matrix.
---@param m matrix
---@return number
function glm.determinant(m) end

---@param ... any
---@return any
function glm.diagonal2x2(...) end

---@param ... any
---@return any
function glm.diagonal2x3(...) end

---@param ... any
---@return any
function glm.diagonal2x4(...) end

---@param ... any
---@return any
function glm.diagonal3x2(...) end

---@param ... any
---@return any
function glm.diagonal3x3(...) end

---@param ... any
---@return any
function glm.diagonal3x4(...) end

---@param ... any
---@return any
function glm.diagonal4x2(...) end

---@param ... any
---@return any
function glm.diagonal4x3(...) end

---@param ... any
---@return any
function glm.diagonal4x4(...) end

---@param ... any
---@return any
function glm.direction(...) end

---@param ... any
---@return any
function glm.direction_to(...) end

---Random point inside a circle of the given radius.
---@param radius number
---@return vector2
function glm.diskRand(radius) end

---Distance between two points.
---@param p0 glm.num
---@param p1 glm.num
---@return number
function glm.distance(p0, p1) end

---Alias of `glm.distance2`. Squared distance between two points.
---@param p0 glm.num
---@param p1 glm.num
---@return number
function glm.distance_squared_to(p0, p1) end

---Alias of `glm.distance`. Distance between two points.
---@param p0 glm.num
---@param p1 glm.num
---@return number
function glm.distance_to(p0, p1) end

---Squared distance between two points.
---@param p0 glm.num
---@param p1 glm.num
---@return number
function glm.distance2(p0, p1) end

---Alias of `glm.distance2`. Squared distance between two points.
---@param p0 glm.num
---@param p1 glm.num
---@return number
function glm.distanceSquared(p0, p1) end

---Dot product.
---@param x glm.vec|quat
---@param y glm.vec|quat
---@return number
function glm.dot(x, y) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.elasticEaseIn(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.elasticEaseInOut(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.elasticEaseOut(t) end

---@param ... any
---@return any
function glm.end(...) end

---Whether `|x - y| < epsilon`, per component.
---@param x glm.num
---@param y glm.num
---@param epsilon glm.num
---@return boolean|glm.vec
function glm.epsilonEqual(x, y, epsilon) end

---@param ... any
---@return any
function glm.epsilonNotEqual(...) end

---Component-wise equality, optionally within `epsilon`.
---@param x any
---@param y any
---@param epsilon? number
---@return boolean|glm.vec
function glm.equal(x, y, epsilon) end

---@param ... any
---@return any
function glm.erf(...) end

---@param ... any
---@return any
function glm.erfc(...) end

---@param ... any
---@return any
function glm.euclidean(...) end

---Pitch, yaw and roll of a quaternion, in radians.
---@param q quat
---@return vector3
function glm.eulerAngles(q) end

---@param ... any
---@return any
function glm.eulerAngleX(...) end

---@param ... any
---@return any
function glm.eulerAngleXY(...) end

---@param ... any
---@return any
function glm.eulerAngleXYX(...) end

---@param ... any
---@return any
function glm.eulerAngleXYZ(...) end

---@param ... any
---@return any
function glm.eulerAngleXZ(...) end

---@param ... any
---@return any
function glm.eulerAngleXZX(...) end

---@param ... any
---@return any
function glm.eulerAngleXZY(...) end

---@param ... any
---@return any
function glm.eulerAngleY(...) end

---@param ... any
---@return any
function glm.eulerAngleYX(...) end

---@param ... any
---@return any
function glm.eulerAngleYXY(...) end

---@param ... any
---@return any
function glm.eulerAngleYXZ(...) end

---@param ... any
---@return any
function glm.eulerAngleYZ(...) end

---@param ... any
---@return any
function glm.eulerAngleYZX(...) end

---@param ... any
---@return any
function glm.eulerAngleYZY(...) end

---@param ... any
---@return any
function glm.eulerAngleZ(...) end

---@param ... any
---@return any
function glm.eulerAngleZX(...) end

---@param ... any
---@return any
function glm.eulerAngleZXY(...) end

---@param ... any
---@return any
function glm.eulerAngleZXZ(...) end

---@param ... any
---@return any
function glm.eulerAngleZY(...) end

---@param ... any
---@return any
function glm.eulerAngleZYX(...) end

---@param ... any
---@return any
function glm.eulerAngleZYZ(...) end

---@param ... any
---@return any
function glm.eulerX(...) end

---@param ... any
---@return any
function glm.eulerXY(...) end

---@param ... any
---@return any
function glm.eulerXYX(...) end

---@param ... any
---@return any
function glm.eulerXYZ(...) end

---@param ... any
---@return any
function glm.eulerXZ(...) end

---@param ... any
---@return any
function glm.eulerXZX(...) end

---@param ... any
---@return any
function glm.eulerXZY(...) end

---@param ... any
---@return any
function glm.eulerY(...) end

---@param ... any
---@return any
function glm.eulerYX(...) end

---@param ... any
---@return any
function glm.eulerYXY(...) end

---@param ... any
---@return any
function glm.eulerYXZ(...) end

---@param ... any
---@return any
function glm.eulerYZ(...) end

---@param ... any
---@return any
function glm.eulerYZX(...) end

---@param ... any
---@return any
function glm.eulerYZY(...) end

---@param ... any
---@return any
function glm.eulerZ(...) end

---@param ... any
---@return any
function glm.eulerZX(...) end

---@param ... any
---@return any
function glm.eulerZXY(...) end

---@param ... any
---@return any
function glm.eulerZXZ(...) end

---@param ... any
---@return any
function glm.eulerZY(...) end

---@param ... any
---@return any
function glm.eulerZYX(...) end

---@param ... any
---@return any
function glm.eulerZYZ(...) end

---Natural exponentiation, per component.
---@param x glm.num
---@return glm.num
function glm.exp(x) end

---`2 ^ x`, per component.
---@param x glm.num
---@return glm.num
function glm.exp2(x) end

---@param ... any
---@return any
function glm.expm1(...) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.exponentialEaseIn(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.exponentialEaseInOut(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.exponentialEaseOut(t) end

---@param ... any
---@return any
function glm.extend(...) end

---@param ... any
---@return any
function glm.extractEulerAngleXYX(...) end

---@param ... any
---@return any
function glm.extractEulerAngleXYZ(...) end

---@param ... any
---@return any
function glm.extractEulerAngleXZX(...) end

---@param ... any
---@return any
function glm.extractEulerAngleXZY(...) end

---@param ... any
---@return any
function glm.extractEulerAngleYXY(...) end

---@param ... any
---@return any
function glm.extractEulerAngleYXZ(...) end

---@param ... any
---@return any
function glm.extractEulerAngleYZX(...) end

---@param ... any
---@return any
function glm.extractEulerAngleYZY(...) end

---@param ... any
---@return any
function glm.extractEulerAngleZXY(...) end

---@param ... any
---@return any
function glm.extractEulerAngleZXZ(...) end

---@param ... any
---@return any
function glm.extractEulerAngleZYX(...) end

---@param ... any
---@return any
function glm.extractEulerAngleZYZ(...) end

---@param ... any
---@return any
function glm.extractMatrixRotation(...) end

---@param ... any
---@return any
function glm.extractRealComponent(...) end

---@param ... any
---@return any
function glm.extractScale(...) end

---Alias of `glm.abs`. Absolute value, per component.
---@param x glm.num
---@return glm.num
function glm.fabs(x) end

---Returns `N` flipped so that it faces against `I`.
---@param N glm.vec
---@param I glm.vec
---@param Nref glm.vec
---@return glm.vec
function glm.faceforward(N, I, Nref) end

---@param ... any
---@return any
function glm.factorial(...) end

---@param ... any
---@return any
function glm.fastAcos(...) end

---@param ... any
---@return any
function glm.fastAsin(...) end

---@param ... any
---@return any
function glm.fastAtan(...) end

---@param ... any
---@return any
function glm.fastCos(...) end

---@param ... any
---@return any
function glm.fastDistance(...) end

---@param ... any
---@return any
function glm.fastExp(...) end

---@param ... any
---@return any
function glm.fastExp2(...) end

---@param ... any
---@return any
function glm.fastInverseSqrt(...) end

---@param ... any
---@return any
function glm.fastLength(...) end

---@param ... any
---@return any
function glm.fastLog(...) end

---@param ... any
---@return any
function glm.fastLog2(...) end

---@param ... any
---@return any
function glm.fastMix(...) end

---@param ... any
---@return any
function glm.fastNormalize(...) end

---@param ... any
---@return any
function glm.fastNormalizeDot(...) end

---@param ... any
---@return any
function glm.fastPow(...) end

---@param ... any
---@return any
function glm.fastSin(...) end

---@param ... any
---@return any
function glm.fastSqrt(...) end

---@param ... any
---@return any
function glm.fastTan(...) end

---@param ... any
---@return any
function glm.fdim(...) end

---@param ... any
---@return any
function glm.findEigenvaluesSymReal(...) end

---@param ... any
---@return any
function glm.findLSB(...) end

---@param ... any
---@return any
function glm.findMSB(...) end

---@param ... any
---@return any
function glm.findNSB(...) end

---@param ... any
---@return any
function glm.fliplr(...) end

---@param ... any
---@return any
function glm.flipud(...) end

---@param ... any
---@return any
function glm.float_distance(...) end

---@param ... any
---@return any
function glm.floatBitsToInt(...) end

---@param ... any
---@return any
function glm.floatBitsToUint(...) end

---Rounds down, per component.
---@param x glm.num
---@return glm.num
function glm.floor(x) end

---@param ... any
---@return any
function glm.floorMultiple(...) end

---@param ... any
---@return any
function glm.floorPowerOfTwo(...) end

---@param ... any
---@return any
function glm.fma(...) end

---@param ... any
---@return any
function glm.fmax(...) end

---@param ... any
---@return any
function glm.fmin(...) end

---Remainder of `x / y` with the sign of `x`, per component.
---@param x glm.num
---@param y glm.num
---@return glm.num
function glm.fmod(x, y) end

---The unit vector pointing forward.
---@return vector3
function glm.forward() end

---@param ... any
---@return any
function glm.forwardLH(...) end

---@param ... any
---@return any
function glm.forwardRH(...) end

---@param ... any
---@return any
function glm.fpclassify(...) end

---Fractional part `x - floor(x)`, per component.
---@param x glm.num
---@return glm.num
function glm.fract(x) end

---@param ... any
---@return any
function glm.frexp(...) end

---@param ... any
---@return any
function glm.from_z(...) end

---@param ... any
---@return any
function glm.frustum(...) end

---@param ... any
---@return any
function glm.frustumLH(...) end

---@param ... any
---@return any
function glm.frustumLH_NO(...) end

---@param ... any
---@return any
function glm.frustumLH_ZO(...) end

---@param ... any
---@return any
function glm.frustumNO(...) end

---@param ... any
---@return any
function glm.frustumRH(...) end

---@param ... any
---@return any
function glm.frustumRH_NO(...) end

---@param ... any
---@return any
function glm.frustumRH_ZO(...) end

---@param ... any
---@return any
function glm.frustumZO(...) end

---@param ... any
---@return any
function glm.gauss(...) end

---@param ... any
---@return any
function glm.gaussRand(...) end

---@param ... any
---@return any
function glm.getColumn(...) end

---@param ... any
---@return any
function glm.getRow(...) end

---@param ... any
---@return any
function glm.greaterThan(...) end

---@param ... any
---@return any
function glm.greaterThanEqual(...) end

---@param ... any
---@return any
function glm.hash(...) end

---@param ... any
---@return any
function glm.hasUniformScale(...) end

---@param ... any
---@return any
function glm.hermite(...) end

---@param ... any
---@return any
function glm.highestBitValue(...) end

---@param ... any
---@return any
function glm.hsvColor(...) end

---@param ... any
---@return any
function glm.hypot(...) end

---Identity matrix.
---@return matrix
function glm.identity() end

---@param ... any
---@return any
function glm.ilogb(...) end

---@param ... any
---@return any
function glm.imulExtended(...) end

---@param ... any
---@return any
function glm.infinitePerspective(...) end

---@param ... any
---@return any
function glm.infinitePerspectiveLH(...) end

---@param ... any
---@return any
function glm.infinitePerspectiveRH(...) end

---@param ... any
---@return any
function glm.intBitsToFloat(...) end

---@param ... any
---@return any
function glm.intermediate(...) end

---@param ... any
---@return any
function glm.interpolate(...) end

---@param ... any
---@return any
function glm.intersectLineSphere(...) end

---@param ... any
---@return any
function glm.intersectLineTriangle(...) end

---@param ... any
---@return any
function glm.intersectRayPlane(...) end

---@param ... any
---@return any
function glm.intersectRaySphere(...) end

---@param ... any
---@return any
function glm.intersectRayTriangle(...) end

---Inverse of a quaternion or matrix.
---@param x quat|matrix
---@return quat|matrix
function glm.inverse(x) end

---`1 / sqrt(x)`, per component.
---@param x glm.num
---@return glm.num
function glm.inversesqrt(x) end

---@param ... any
---@return any
function glm.inverseTranspose(...) end

---@param ... any
---@return any
function glm.invertible(...) end

---@param ... any
---@return any
function glm.iround(...) end

---@param ... any
---@return any
function glm.is_normalized(...) end

---@param ... any
---@return any
function glm.isCompNull(...) end

---@param ... any
---@return any
function glm.isdenormal(...) end

---@param ... any
---@return any
function glm.isEmpty(...) end

---@param ... any
---@return any
function glm.isfinite(...) end

---@param ... any
---@return any
function glm.isgreater(...) end

---@param ... any
---@return any
function glm.isgreaterequal(...) end

---@param ... any
---@return any
function glm.isIdentity(...) end

---Whether the value is infinite, per component.
---@param x glm.num
---@return boolean|glm.vec
function glm.isinf(x) end

---@param ... any
---@return any
function glm.isless(...) end

---@param ... any
---@return any
function glm.islessequal(...) end

---@param ... any
---@return any
function glm.isMultiple(...) end

---Whether the value is NaN, per component.
---@param x glm.num
---@return boolean|glm.vec
function glm.isnan(x) end

---@param ... any
---@return any
function glm.isnormal(...) end

---@param ... any
---@return any
function glm.isNormalized(...) end

---@param ... any
---@return any
function glm.isNull(...) end

---@param ... any
---@return any
function glm.isOrthogonal(...) end

---@param ... any
---@return any
function glm.isPerpendicular(...) end

---@param ... any
---@return any
function glm.isPowerOfTwo(...) end

---@param ... any
---@return any
function glm.isUniform(...) end

---@param ... any
---@return any
function glm.isunordered(...) end

---@param ... any
---@return any
function glm.isZero(...) end

---@param ... any
---@return any
function glm.ivec(...) end

---@param ... any
---@return any
function glm.ivec1(...) end

---Builds a vector2 with every component truncated to an integer.
---@param ... number|glm.vec|quat|matrix
---@return vector2
function glm.ivec2(...) end

---Builds a vector3 with every component truncated to an integer.
---@param ... number|glm.vec|quat|matrix
---@return vector3
function glm.ivec3(...) end

---Builds a vector4 with every component truncated to an integer.
---@param ... number|glm.vec|quat|matrix
---@return vector4
function glm.ivec4(...) end

---@param ... any
---@return any
function glm.l1Norm(...) end

---@param ... any
---@return any
function glm.l2Norm(...) end

---@param ... any
---@return any
function glm.ldexp(...) end

---@param ... any
---@return any
function glm.leftHanded(...) end

---Length of a vector or quaternion.
---@param x glm.num|quat
---@return number
function glm.length(x) end

---Alias of `glm.length2`. Squared length, which avoids the square root.
---@param x glm.num|quat
---@return number
function glm.length_squared(x) end

---Squared length, which avoids the square root.
---@param x glm.num|quat
---@return number
function glm.length2(x) end

---Alias of `glm.length2`. Squared length, which avoids the square root.
---@param x glm.num|quat
---@return number
function glm.lengthSquared(x) end

---Linear interpolation between `x` and `y`.
---@param x glm.num|quat
---@param y glm.num|quat
---@param a glm.num
---@return glm.num|quat
function glm.lerp(x, y, a) end

---@param ... any
---@return any
function glm.lerpAngle(...) end

---@param ... any
---@return any
function glm.lessThan(...) end

---@param ... any
---@return any
function glm.lessThanEqual(...) end

---@param ... any
---@return any
function glm.levels(...) end

---@param ... any
---@return any
function glm.lgamma(...) end

---@param ... any
---@return any
function glm.linearGradient(...) end

---@param ... any
---@return any
function glm.linearInterpolation(...) end

---Uniformly distributed random value between `min` and `max`, per component.
---@param min glm.num
---@param max glm.num
---@return glm.num
function glm.linearRand(min, max) end

---@param ... any
---@return any
function glm.lMaxNorm(...) end

---Natural logarithm, per component.
---@param x glm.num
---@return glm.num
function glm.log(x) end

---@param ... any
---@return any
function glm.log10(...) end

---@param ... any
---@return any
function glm.log1p(...) end

---Base 2 logarithm, per component.
---@param x glm.num
---@return glm.num
function glm.log2(x) end

---@param ... any
---@return any
function glm.logb(...) end

---View matrix for a camera at `eye` looking at `center`.
---@param eye vector3
---@param center vector3
---@param up vector3
---@return matrix
function glm.lookAt(eye, center, up) end

---@param ... any
---@return any
function glm.lookAtLH(...) end

---@param ... any
---@return any
function glm.lookAtRH(...) end

---@param ... any
---@return any
function glm.lookRotation(...) end

---@param ... any
---@return any
function glm.lookRotationLH(...) end

---@param ... any
---@return any
function glm.lookRotationRH(...) end

---@param ... any
---@return any
function glm.loopRepeat(...) end

---@param ... any
---@return any
function glm.lowestBitValue(...) end

---@param ... any
---@return any
function glm.luminosity(...) end

---@param ... any
---@return any
function glm.lxNorm(...) end

---Alias of `glm.length`. Length of a vector or quaternion.
---@param x glm.num|quat
---@return number
function glm.magnitude(x) end

---@param ... any
---@return any
function glm.mask(...) end

---Builds a matrix whose size follows from the arguments.
---@param ... number|glm.vec|quat|matrix
---@return matrix
function glm.mat(...) end

---@param ... any
---@return any
function glm.mat_add(...) end

---@param ... any
---@return any
function glm.mat_mul(...) end

---@param ... any
---@return any
function glm.mat_negate(...) end

---@param ... any
---@return any
function glm.mat_sub(...) end

---Builds a 2x2 matrix.
---@param ... number|glm.vec|quat|matrix
---@return matrix
function glm.mat2(...) end

---@param ... any
---@return any
function glm.mat2x2(...) end

---@param ... any
---@return any
function glm.mat2x3(...) end

---@param ... any
---@return any
function glm.mat2x4(...) end

---Builds a 3x3 matrix from numbers, column vectors or a quaternion.
---@param ... number|glm.vec|quat|matrix
---@return matrix
function glm.mat3(...) end

---Rotation matrix of a quaternion.
---@param q quat
---@return matrix
function glm.mat3_cast(q) end

---@param ... any
---@return any
function glm.mat3x2(...) end

---@param ... any
---@return any
function glm.mat3x3(...) end

---@param ... any
---@return any
function glm.mat3x4(...) end

---Builds a 4x4 matrix from numbers, column vectors or a quaternion.
---@param ... number|glm.vec|quat|matrix
---@return matrix
function glm.mat4(...) end

---Rotation matrix of a quaternion.
---@param q quat
---@return matrix
function glm.mat4_cast(q) end

---@param ... any
---@return any
function glm.mat4x2(...) end

---@param ... any
---@return any
function glm.mat4x3(...) end

---@param ... any
---@return any
function glm.mat4x4(...) end

---@param ... any
---@return any
function glm.matrixCompMult(...) end

---@param ... any
---@return any
function glm.matrixCross3(...) end

---@param ... any
---@return any
function glm.matrixCross4(...) end

---Largest of the arguments, per component.
---@param x glm.num
---@param y glm.num
---@param ... glm.num
---@return glm.num
function glm.max(x, y, ...) end

---Smallest of the arguments, per component.
---@param x glm.num
---@param y glm.num
---@param ... glm.num
---@return glm.num
function glm.min(x, y, ...) end

---@param ... any
---@return any
function glm.mirrorClamp(...) end

---@param ... any
---@return any
function glm.mirrorRepeat(...) end

---Linear blend `x * (1 - a) + y * a`. Quaternions are blended spherically.
---@param x glm.num|quat
---@param y glm.num|quat
---@param a glm.num
---@return glm.num|quat
function glm.mix(x, y, a) end

---@param ... any
---@return any
function glm.mixedProduct(...) end

---Modulus `x - y * floor(x / y)`, per component.
---@param x glm.num
---@param y glm.num
---@return glm.num
function glm.mod(x, y) end

---@param ... any
---@return any
function glm.modf(...) end

---@param ... any
---@return any
function glm.move_toward(...) end

---@param ... any
---@return any
function glm.moveTowards(...) end

---@param ... any
---@return any
function glm.nearbyint(...) end

---@param ... any
---@return any
function glm.next_float(...) end

---@param ... any
---@return any
function glm.nextafter(...) end

---@param ... any
---@return any
function glm.nextMultiple(...) end

---@param ... any
---@return any
function glm.nextPowerOfTwo(...) end

---@param ... any
---@return any
function glm.nlz(...) end

---Alias of `glm.normalize`. Same direction, length 1.
---@param x glm.vec|quat
---@return glm.vec|quat
function glm.norm(x) end

---Same direction, length 1.
---@param x glm.vec|quat
---@return glm.vec|quat
function glm.normalize(x) end

---@param ... any
---@return any
function glm.normalizeDot(...) end

---@param ... any
---@return any
function glm.not_(...) end

---Component-wise inequality, optionally outside `epsilon`.
---@param x any
---@param y any
---@param epsilon? number
---@return boolean|glm.vec
function glm.notEqual(x, y, epsilon) end

---@param ... any
---@return any
function glm.openBounded(...) end

---@param ... any
---@return any
function glm.orientate2(...) end

---@param ... any
---@return any
function glm.orientate3(...) end

---@param ... any
---@return any
function glm.orientate4(...) end

---@param ... any
---@return any
function glm.orientation(...) end

---@param ... any
---@return any
function glm.orientedAngle(...) end

---Orthographic projection matrix.
---@param left number
---@param right number
---@param bottom number
---@param top number
---@param near? number
---@param far? number
---@return matrix
function glm.ortho(left, right, bottom, top, near, far) end

---@param ... any
---@return any
function glm.orthoLH(...) end

---@param ... any
---@return any
function glm.orthoLH_NO(...) end

---@param ... any
---@return any
function glm.orthoLH_ZO(...) end

---@param ... any
---@return any
function glm.orthoNO(...) end

---@param ... any
---@return any
function glm.orthonormalize(...) end

---@param ... any
---@return any
function glm.orthonormalize3(...) end

---@param ... any
---@return any
function glm.orthoRH(...) end

---@param ... any
---@return any
function glm.orthoRH_NO(...) end

---@param ... any
---@return any
function glm.orthoRH_ZO(...) end

---@param ... any
---@return any
function glm.orthoZO(...) end

---@param ... any
---@return any
function glm.outerProduct(...) end

---@param ... any
---@return any
function glm.packDouble2x32(...) end

---@param ... any
---@return any
function glm.packF2x11_1x10(...) end

---@param ... any
---@return any
function glm.packF3x9_E1x5(...) end

---@param ... any
---@return any
function glm.packHalf(...) end

---@param ... any
---@return any
function glm.packHalf1x16(...) end

---@param ... any
---@return any
function glm.packHalf2x16(...) end

---@param ... any
---@return any
function glm.packHalf4x16(...) end

---@param ... any
---@return any
function glm.packI3x10_1x2(...) end

---@param ... any
---@return any
function glm.packInt2x16(...) end

---@param ... any
---@return any
function glm.packInt2x32(...) end

---@param ... any
---@return any
function glm.packInt2x8(...) end

---@param ... any
---@return any
function glm.packInt4x16(...) end

---@param ... any
---@return any
function glm.packInt4x8(...) end

---@param ... any
---@return any
function glm.packRGBM(...) end

---@param ... any
---@return any
function glm.packSnorm(...) end

---@param ... any
---@return any
function glm.packSnorm1x16(...) end

---@param ... any
---@return any
function glm.packSnorm1x8(...) end

---@param ... any
---@return any
function glm.packSnorm2x16(...) end

---@param ... any
---@return any
function glm.packSnorm2x8(...) end

---@param ... any
---@return any
function glm.packSnorm3x10_1x2(...) end

---@param ... any
---@return any
function glm.packSnorm4x16(...) end

---@param ... any
---@return any
function glm.packSnorm4x8(...) end

---@param ... any
---@return any
function glm.packU3x10_1x2(...) end

---@param ... any
---@return any
function glm.packUint2x16(...) end

---@param ... any
---@return any
function glm.packUint2x32(...) end

---@param ... any
---@return any
function glm.packUint2x8(...) end

---@param ... any
---@return any
function glm.packUint4x16(...) end

---@param ... any
---@return any
function glm.packUint4x8(...) end

---@param ... any
---@return any
function glm.packUnorm(...) end

---@param ... any
---@return any
function glm.packUnorm1x16(...) end

---@param ... any
---@return any
function glm.packUnorm1x5_1x6_1x5(...) end

---@param ... any
---@return any
function glm.packUnorm1x8(...) end

---@param ... any
---@return any
function glm.packUnorm2x16(...) end

---@param ... any
---@return any
function glm.packUnorm2x3_1x2(...) end

---@param ... any
---@return any
function glm.packUnorm2x4(...) end

---@param ... any
---@return any
function glm.packUnorm2x8(...) end

---@param ... any
---@return any
function glm.packUnorm3x10_1x2(...) end

---@param ... any
---@return any
function glm.packUnorm3x5_1x1(...) end

---@param ... any
---@return any
function glm.packUnorm4x16(...) end

---@param ... any
---@return any
function glm.packUnorm4x4(...) end

---@param ... any
---@return any
function glm.packUnorm4x8(...) end

---@param ... any
---@return any
function glm.perlin(...) end

---@param ... any
---@return any
function glm.perp(...) end

---@param ... any
---@return any
function glm.perpendicular(...) end

---@param ... any
---@return any
function glm.perpendicular2(...) end

---@param ... any
---@return any
function glm.perpendicularBasis(...) end

---@param ... any
---@return any
function glm.perpendicularFast(...) end

---Perspective projection matrix; `fovy` is in radians.
---@param fovy number
---@param aspect number
---@param near number
---@param far number
---@return matrix
function glm.perspective(fovy, aspect, near, far) end

---@param ... any
---@return any
function glm.perspectiveFov(...) end

---@param ... any
---@return any
function glm.perspectiveFovLH(...) end

---@param ... any
---@return any
function glm.perspectiveFovLH_NO(...) end

---@param ... any
---@return any
function glm.perspectiveFovLH_ZO(...) end

---@param ... any
---@return any
function glm.perspectiveFovNO(...) end

---@param ... any
---@return any
function glm.perspectiveFovRH(...) end

---@param ... any
---@return any
function glm.perspectiveFovRH_NO(...) end

---@param ... any
---@return any
function glm.perspectiveFovRH_ZO(...) end

---@param ... any
---@return any
function glm.perspectiveFovZO(...) end

---@param ... any
---@return any
function glm.perspectiveLH(...) end

---@param ... any
---@return any
function glm.perspectiveLH_NO(...) end

---@param ... any
---@return any
function glm.perspectiveLH_ZO(...) end

---@param ... any
---@return any
function glm.perspectiveNO(...) end

---@param ... any
---@return any
function glm.perspectiveRH(...) end

---@param ... any
---@return any
function glm.perspectiveRH_NO(...) end

---@param ... any
---@return any
function glm.perspectiveRH_ZO(...) end

---@param ... any
---@return any
function glm.perspectiveZO(...) end

---@param ... any
---@return any
function glm.pickMatrix(...) end

---@param ... any
---@return any
function glm.pingPong(...) end

---Pitch of a quaternion in radians.
---@param q quat
---@return number
function glm.pitch(q) end

---@param ... any
---@return any
function glm.polar(...) end

---`base ^ exponent`, per component.
---@param base glm.num
---@param exponent glm.num
---@return glm.num
function glm.pow(base, exponent) end

---@param ... any
---@return any
function glm.pow2(...) end

---@param ... any
---@return any
function glm.pow3(...) end

---@param ... any
---@return any
function glm.pow4(...) end

---@param ... any
---@return any
function glm.prev_float(...) end

---@param ... any
---@return any
function glm.prevMultiple(...) end

---@param ... any
---@return any
function glm.prevPowerOfTwo(...) end

---@param ... any
---@return any
function glm.proj(...) end

---@param ... any
---@return any
function glm.proj2D(...) end

---@param ... any
---@return any
function glm.proj3D(...) end

---@param ... any
---@return any
function glm.projDecompose(...) end

---@param ... any
---@return any
function glm.project(...) end

---@param ... any
---@return any
function glm.projectNO(...) end

---@param ... any
---@return any
function glm.projectZO(...) end

---@param ... any
---@return any
function glm.projNorm(...) end

---@param ... any
---@return any
function glm.projPlane(...) end

---@param ... any
---@return any
function glm.qr_decompose(...) end

---Alias of `glm.quat`.
---@param ... number|glm.vec|quat|matrix
---@return quat
function glm.qua(...) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.quadraticEaseIn(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.quadraticEaseInOut(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.quadraticEaseOut(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.quarticEaseIn(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.quarticEaseInOut(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.quarticEaseOut(t) end

---Builds a quaternion from `w, x, y, z`, an angle and axis, two directions, or a rotation matrix.
---@param ... number|glm.vec|quat|matrix
---@return quat
function glm.quat(...) end

---Quaternion of a rotation matrix.
---@param m matrix
---@return quat
function glm.quat_cast(m) end

---@param ... any
---@return any
function glm.quat_identity(...) end

---@param ... any
---@return any
function glm.quatbillboard(...) end

---@param ... any
---@return any
function glm.quatbillboardLH(...) end

---@param ... any
---@return any
function glm.quatbillboardRH(...) end

---@param ... any
---@return any
function glm.quatEulerAngleX(...) end

---@param ... any
---@return any
function glm.quatEulerAngleXY(...) end

---@param ... any
---@return any
function glm.quatEulerAngleXYX(...) end

---@param ... any
---@return any
function glm.quatEulerAngleXYZ(...) end

---@param ... any
---@return any
function glm.quatEulerAngleXZ(...) end

---@param ... any
---@return any
function glm.quatEulerAngleXZX(...) end

---@param ... any
---@return any
function glm.quatEulerAngleXZY(...) end

---@param ... any
---@return any
function glm.quatEulerAngleY(...) end

---@param ... any
---@return any
function glm.quatEulerAngleYX(...) end

---@param ... any
---@return any
function glm.quatEulerAngleYXY(...) end

---@param ... any
---@return any
function glm.quatEulerAngleYXZ(...) end

---@param ... any
---@return any
function glm.quatEulerAngleYZ(...) end

---@param ... any
---@return any
function glm.quatEulerAngleYZX(...) end

---@param ... any
---@return any
function glm.quatEulerAngleYZY(...) end

---@param ... any
---@return any
function glm.quatEulerAngleZ(...) end

---@param ... any
---@return any
function glm.quatEulerAngleZX(...) end

---@param ... any
---@return any
function glm.quatEulerAngleZXY(...) end

---@param ... any
---@return any
function glm.quatEulerAngleZXZ(...) end

---@param ... any
---@return any
function glm.quatEulerAngleZY(...) end

---@param ... any
---@return any
function glm.quatEulerAngleZYX(...) end

---@param ... any
---@return any
function glm.quatEulerAngleZYZ(...) end

---Quaternion that looks along `direction` with the given `up` vector.
---@param direction vector3
---@param up vector3
---@return quat
function glm.quatLookAt(direction, up) end

---@param ... any
---@return any
function glm.quatLookAtLH(...) end

---@param ... any
---@return any
function glm.quatLookAtRH(...) end

---@param ... any
---@return any
function glm.quatlookRotation(...) end

---@param ... any
---@return any
function glm.quatlookRotationLH(...) end

---@param ... any
---@return any
function glm.quatlookRotationRH(...) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.quinticEaseIn(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.quinticEaseInOut(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.quinticEaseOut(t) end

---Alias of `glm.radians`. Converts degrees to radians, per component.
---@param x glm.num
---@return glm.num
function glm.rad(x) end

---@param ... any
---@return any
function glm.radialGradient(...) end

---Converts degrees to radians, per component.
---@param x glm.num
---@return glm.num
function glm.radians(x) end

---@param ... any
---@return any
function glm.random(...) end

---@param ... any
---@return any
function glm.randomseed(...) end

---@param ... any
---@return any
function glm.rayPicking(...) end

---Reflects the incident vector `I` around the normal `N`.
---@param I glm.vec
---@param N glm.vec
---@return glm.vec
function glm.reflect(I, N) end

---Refracts `I` through a surface with normal `N` and ratio of indices `eta`.
---@param I glm.vec
---@param N glm.vec
---@param eta number
---@return glm.vec
function glm.refract(I, N, eta) end

---@param ... any
---@return any
function glm.remainder(...) end

---@param ... any
---@return any
function glm.remquo(...) end

---@param ... any
---@return any
function glm.repeat(...) end

---@param ... any
---@return any
function glm.reverse(...) end

---@param ... any
---@return any
function glm.rgb2YCoCg(...) end

---@param ... any
---@return any
function glm.rgb2YCoCgR(...) end

---@param ... any
---@return any
function glm.rgbColor(...) end

---The unit vector pointing right.
---@return vector3
function glm.right() end

---@param ... any
---@return any
function glm.rightHanded(...) end

---Roll of a quaternion in radians.
---@param q quat
---@return number
function glm.roll(q) end

---Rotates a vector by a quaternion, or a quaternion/matrix by `angle` radians around `axis`.
---@param x quat|matrix|glm.vec
---@param angle number|glm.vec
---@param axis? vector3
---@return quat|matrix|glm.vec
function glm.rotate(x, angle, axis) end

---@param ... any
---@return any
function glm.rotateFromTo(...) end

---@param ... any
---@return any
function glm.rotateNormalizedAxis(...) end

---@param ... any
---@return any
function glm.rotateTowards(...) end

---@param ... any
---@return any
function glm.rotateX(...) end

---@param ... any
---@return any
function glm.rotateY(...) end

---@param ... any
---@return any
function glm.rotateZ(...) end

---@param ... any
---@return any
function glm.rotation(...) end

---Rounds to the nearest integer, per component.
---@param x glm.num
---@return glm.num
function glm.round(x) end

---@param ... any
---@return any
function glm.roundEven(...) end

---@param ... any
---@return any
function glm.roundMultiple(...) end

---@param ... any
---@return any
function glm.roundPowerOfTwo(...) end

---@param ... any
---@return any
function glm.row(...) end

---@param ... any
---@return any
function glm.rowMajor(...) end

---@param ... any
---@return any
function glm.rowMajor2(...) end

---@param ... any
---@return any
function glm.rowMajor3(...) end

---@param ... any
---@return any
function glm.rowMajor4(...) end

---@param ... any
---@return any
function glm.rq_decompose(...) end

---Clamps to the range 0..1, per component.
---@param x glm.num
---@return glm.num
function glm.saturate(x) end

---@param ... any
---@return any
function glm.saturation(...) end

---@param ... any
---@return any
function glm.scalbn(...) end

---Appends a scale to a matrix.
---@param m matrix
---@param v vector3
---@return matrix
function glm.scale(m, v) end

---@param ... any
---@return any
function glm.scaleBias(...) end

---@param ... any
---@return any
function glm.scaleLength(...) end

---@param ... any
---@return any
function glm.scaleMagnitude(...) end

---@param ... any
---@return any
function glm.sec(...) end

---@param ... any
---@return any
function glm.sech(...) end

---@param ... any
---@return any
function glm.shearX(...) end

---@param ... any
---@return any
function glm.shearX2D(...) end

---@param ... any
---@return any
function glm.shearX3D(...) end

---@param ... any
---@return any
function glm.shearY(...) end

---@param ... any
---@return any
function glm.shearY2D(...) end

---@param ... any
---@return any
function glm.shearY3D(...) end

---@param ... any
---@return any
function glm.shearZ3D(...) end

---@param ... any
---@return any
function glm.shortMix(...) end

----1, 0 or 1 depending on the sign, per component.
---@param x glm.num
---@return glm.num
function glm.sign(x) end

---Alias of `glm.sign`. -1, 0 or 1 depending on the sign, per component.
---@param x glm.num
---@return glm.num
function glm.signbit(x) end

---@param ... any
---@return any
function glm.signed_angle_to(...) end

---@param ... any
---@return any
function glm.signedAngle(...) end

---@param ... any
---@return any
function glm.signN(...) end

---@param ... any
---@return any
function glm.signP(...) end

---@param ... any
---@return any
function glm.simplex(...) end

---Sine of an angle in radians, per component.
---@param x glm.num
---@return glm.num
function glm.sin(x) end

---@param ... any
---@return any
function glm.sincos(...) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.sineEaseIn(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.sineEaseInOut(t) end

---Easing curve for `t` in the range 0..1.
---@param t number
---@return number
function glm.sineEaseOut(t) end

---Hyperbolic sine, per component.
---@param x glm.num
---@return glm.num
function glm.sinh(x) end

---Spherical interpolation between two quaternions or directions.
---@param x quat|glm.vec
---@param y quat|glm.vec
---@param a number
---@return quat|glm.vec
function glm.slerp(x, y, a) end

---@param ... any
---@return any
function glm.smoothDamp(...) end

---Hermite interpolation between 0 and 1 while `x` moves from `edge0` to `edge1`.
---@param edge0 glm.num
---@param edge1 glm.num
---@param x glm.num
---@return glm.num
function glm.smoothstep(edge0, edge1, x) end

---@param ... any
---@return any
function glm.snap(...) end

---Random point on a sphere of the given radius.
---@param radius number
---@return vector3
function glm.sphericalRand(radius) end

---Alias of `glm.length2`. Squared length, which avoids the square root.
---@param x glm.num|quat
---@return number
function glm.sqrLength(x) end

---Alias of `glm.length2`. Squared length, which avoids the square root.
---@param x glm.num|quat
---@return number
function glm.sqrMagnitude(x) end

---Square root, per component.
---@param x glm.num
---@return glm.num
function glm.sqrt(x) end

---@param ... any
---@return any
function glm.squad(...) end

---@param ... any
---@return any
function glm.srand(...) end

---0 where `x < edge`, otherwise 1, per component.
---@param edge glm.num
---@param x glm.num
---@return glm.num
function glm.step(edge, x) end

---Tangent of an angle in radians, per component.
---@param x glm.num
---@return glm.num
function glm.tan(x) end

---Hyperbolic tangent, per component.
---@param x glm.num
---@return glm.num
function glm.tanh(x) end

---@param ... any
---@return any
function glm.tgamma(...) end

---Human readable text for a vector, quaternion or matrix.
---@param x any
---@return string
function glm.to_string(x) end

---Converts to an integer when the value has an exact integer representation, per component.
---@param x glm.num
---@return integer|glm.vec
function glm.toint(x) end

---Alias of `glm.toint`. Converts to an integer when the value has an exact integer representation, per component.
---@param x glm.num
---@return integer|glm.vec
function glm.tointeger(x) end

---Rotation matrix of a quaternion.
---@param q quat
---@return matrix
function glm.toMat3(q) end

---Rotation matrix of a quaternion.
---@param q quat
---@return matrix
function glm.toMat4(q) end

---Quaternion of a rotation matrix.
---@param m matrix
---@return quat
function glm.toQuat(m) end

---@param ... any
---@return any
function glm.transformDir(...) end

---@param ... any
---@return any
function glm.transformPos(...) end

---@param ... any
---@return any
function glm.transformPosPerspective(...) end

---Appends a translation to a matrix.
---@param m matrix
---@param v vector3
---@return matrix
function glm.translate(m, v) end

---Transposed matrix.
---@param m matrix
---@return matrix
function glm.transpose(m) end

---@param ... any
---@return any
function glm.triangleNormal(...) end

---@param ... any
---@return any
function glm.trs(...) end

---Drops the fractional part, per component.
---@param x glm.num
---@return glm.num
function glm.trunc(x) end

---@param ... any
---@return any
function glm.tweakedInfinitePerspective(...) end

---@param ... any
---@return any
function glm.type(...) end

---@param ... any
---@return any
function glm.uaddCarry(...) end

---@param ... any
---@return any
function glm.uintBitsToFloat(...) end

---@param ... any
---@return any
function glm.ult(...) end

---@param ... any
---@return any
function glm.ulte(...) end

---@param ... any
---@return any
function glm.umulExtended(...) end

---Returns the components of vectors, quaternions and matrices as separate values.
---@param ... any
---@return number ...
function glm.unpack(...) end

---@param ... any
---@return any
function glm.unpackDouble2x32(...) end

---@param ... any
---@return any
function glm.unpackF2x11_1x10(...) end

---@param ... any
---@return any
function glm.unpackF3x9_E1x5(...) end

---@param ... any
---@return any
function glm.unpackHalf(...) end

---@param ... any
---@return any
function glm.unpackHalf1x16(...) end

---@param ... any
---@return any
function glm.unpackHalf2x16(...) end

---@param ... any
---@return any
function glm.unpackHalf4x16(...) end

---@param ... any
---@return any
function glm.unpackI3x10_1x2(...) end

---@param ... any
---@return any
function glm.unpackInt2x16(...) end

---@param ... any
---@return any
function glm.unpackInt2x32(...) end

---@param ... any
---@return any
function glm.unpackInt2x8(...) end

---@param ... any
---@return any
function glm.unpackInt4x16(...) end

---@param ... any
---@return any
function glm.unpackInt4x8(...) end

---@param ... any
---@return any
function glm.unpackRGBM(...) end

---@param ... any
---@return any
function glm.unpackSnorm(...) end

---@param ... any
---@return any
function glm.unpackSnorm1x16(...) end

---@param ... any
---@return any
function glm.unpackSnorm1x8(...) end

---@param ... any
---@return any
function glm.unpackSnorm2x16(...) end

---@param ... any
---@return any
function glm.unpackSnorm2x8(...) end

---@param ... any
---@return any
function glm.unpackSnorm3x10_1x2(...) end

---@param ... any
---@return any
function glm.unpackSnorm4x16(...) end

---@param ... any
---@return any
function glm.unpackSnorm4x8(...) end

---@param ... any
---@return any
function glm.unpackU3x10_1x2(...) end

---@param ... any
---@return any
function glm.unpackUint2x16(...) end

---@param ... any
---@return any
function glm.unpackUint2x32(...) end

---@param ... any
---@return any
function glm.unpackUint2x8(...) end

---@param ... any
---@return any
function glm.unpackUint4x16(...) end

---@param ... any
---@return any
function glm.unpackUint4x8(...) end

---@param ... any
---@return any
function glm.unpackUnorm(...) end

---@param ... any
---@return any
function glm.unpackUnorm1x16(...) end

---@param ... any
---@return any
function glm.unpackUnorm1x5_1x6_1x5(...) end

---@param ... any
---@return any
function glm.unpackUnorm1x8(...) end

---@param ... any
---@return any
function glm.unpackUnorm2x16(...) end

---@param ... any
---@return any
function glm.unpackUnorm2x3_1x2(...) end

---@param ... any
---@return any
function glm.unpackUnorm2x4(...) end

---@param ... any
---@return any
function glm.unpackUnorm2x8(...) end

---@param ... any
---@return any
function glm.unpackUnorm3x10_1x2(...) end

---@param ... any
---@return any
function glm.unpackUnorm3x5_1x1(...) end

---@param ... any
---@return any
function glm.unpackUnorm4x16(...) end

---@param ... any
---@return any
function glm.unpackUnorm4x4(...) end

---@param ... any
---@return any
function glm.unpackUnorm4x8(...) end

---@param ... any
---@return any
function glm.unProject(...) end

---@param ... any
---@return any
function glm.unProjectNO(...) end

---@param ... any
---@return any
function glm.unProjectZO(...) end

---The unit vector pointing up.
---@return vector3
function glm.up() end

---@param ... any
---@return any
function glm.uround(...) end

---@param ... any
---@return any
function glm.usubBorrow(...) end

---Builds a vector whose size follows from the arguments.
---@param ... number|glm.vec|quat|matrix
---@return glm.vec
function glm.vec(...) end

---Builds a one component vector, which CfxLua represents as a number.
---@param ... number|glm.vec|quat|matrix
---@return number
function glm.vec1(...) end

---Builds a vector2 from numbers and/or other vectors.
---@param ... number|glm.vec|quat|matrix
---@return vector2
function glm.vec2(...) end

---Builds a vector3 from numbers and/or other vectors.
---@param ... number|glm.vec|quat|matrix
---@return vector3
function glm.vec3(...) end

---Builds a vector4 from numbers and/or other vectors.
---@param ... number|glm.vec|quat|matrix
---@return vector4
function glm.vec4(...) end

---@param ... any
---@return any
function glm.wrapAngle(...) end

---Yaw of a quaternion in radians.
---@param q quat
---@return number
function glm.yaw(q) end

---@param ... any
---@return any
function glm.yawPitchRoll(...) end

---@param ... any
---@return any
function glm.YCoCg2rgb(...) end

---@param ... any
---@return any
function glm.YCoCgR2rgb(...) end

---Geometry helpers for aabb shapes.
---@class glm.aabb
glm.aabb = {}

---@param ... any
---@return any
function glm.aabb.aabbFromSphere(...) end

---@param ... any
---@return any
function glm.aabb.centerPoint(...) end

---@param ... any
---@return any
function glm.aabb.centroid(...) end

---@param ... any
---@return any
function glm.aabb.closestPoint(...) end

---@param ... any
---@return any
function glm.aabb.contains(...) end

---@param ... any
---@return any
function glm.aabb.containsAABB(...) end

---@param ... any
---@return any
function glm.aabb.containsPolygon(...) end

---@param ... any
---@return any
function glm.aabb.containsSegment(...) end

---@param ... any
---@return any
function glm.aabb.containsSphere(...) end

---@param ... any
---@return any
function glm.aabb.containsTriangle(...) end

---@param ... any
---@return any
function glm.aabb.cornerPoint(...) end

---@param ... any
---@return any
function glm.aabb.diagonal(...) end

---@param ... any
---@return any
function glm.aabb.distance(...) end

---@param ... any
---@return any
function glm.aabb.distanceSphere(...) end

---@param ... any
---@return any
function glm.aabb.edge(...) end

---@param ... any
---@return any
function glm.aabb.enclose(...) end

---@param ... any
---@return any
function glm.aabb.encloseAABB(...) end

---@param ... any
---@return any
function glm.aabb.enclosePolygon(...) end

---@param ... any
---@return any
function glm.aabb.encloseSegment(...) end

---@param ... any
---@return any
function glm.aabb.encloseSphere(...) end

---@param ... any
---@return any
function glm.aabb.encloseTriangle(...) end

---@param ... any
---@return any
function glm.aabb.equal(...) end

---@param ... any
---@return any
function glm.aabb.extremePoint(...) end

---@param ... any
---@return any
function glm.aabb.faceCenterPoint(...) end

---@param ... any
---@return any
function glm.aabb.faceNormal(...) end

---@param ... any
---@return any
function glm.aabb.facePlane(...) end

---@param ... any
---@return any
function glm.aabb.facePoint(...) end

---@param ... any
---@return any
function glm.aabb.fromCenterAndSize(...) end

---@param ... any
---@return any
function glm.aabb.grow(...) end

---@param ... any
---@return any
function glm.aabb.halfDiagonal(...) end

---@param ... any
---@return any
function glm.aabb.halfSize(...) end

---@param ... any
---@return any
function glm.aabb.intersectAABB(...) end

---@param ... any
---@return any
function glm.aabb.intersection(...) end

---@param ... any
---@return any
function glm.aabb.intersectLine(...) end

---@param ... any
---@return any
function glm.aabb.intersectPlane(...) end

---@param ... any
---@return any
function glm.aabb.intersectRay(...) end

---@param ... any
---@return any
function glm.aabb.intersectsAABB(...) end

---@param ... any
---@return any
function glm.aabb.intersectSegment(...) end

---@param ... any
---@return any
function glm.aabb.intersectsLine(...) end

---@param ... any
---@return any
function glm.aabb.intersectSphere(...) end

---@param ... any
---@return any
function glm.aabb.intersectsPlane(...) end

---@param ... any
---@return any
function glm.aabb.intersectsRay(...) end

---@param ... any
---@return any
function glm.aabb.intersectsSegment(...) end

---@param ... any
---@return any
function glm.aabb.intersectsSphere(...) end

---@param ... any
---@return any
function glm.aabb.intersectsTriangle(...) end

---@param ... any
---@return any
function glm.aabb.isDegenerate(...) end

---@param ... any
---@return any
function glm.aabb.isfinite(...) end

---@param ... any
---@return any
function glm.aabb.isinf(...) end

---@param ... any
---@return any
function glm.aabb.isnan(...) end

---@param ... any
---@return any
function glm.aabb.maximalContainedSphere(...) end

---@param ... any
---@return any
function glm.aabb.minimalEnclosingSphere(...) end

---@param ... any
---@return any
function glm.aabb.new(...) end

---@param ... any
---@return any
function glm.aabb.notEqual(...) end

---@param ... any
---@return any
function glm.aabb.pointInside(...) end

---@param ... any
---@return any
function glm.aabb.pointOnEdge(...) end

---@param ... any
---@return any
function glm.aabb.projectToAxis(...) end

---@param ... any
---@return any
function glm.aabb.scale(...) end

---@param ... any
---@return any
function glm.aabb.size(...) end

---@param ... any
---@return any
function glm.aabb.slabs(...) end

---@param ... any
---@return any
function glm.aabb.surfaceArea(...) end

---@param ... any
---@return any
function glm.aabb.volume(...) end

---Geometry helpers for aabb2d shapes.
---@class glm.aabb2d
glm.aabb2d = {}

---@param ... any
---@return any
function glm.aabb2d.aabbFromSphere(...) end

---@param ... any
---@return any
function glm.aabb2d.centerPoint(...) end

---@param ... any
---@return any
function glm.aabb2d.centroid(...) end

---@param ... any
---@return any
function glm.aabb2d.closestPoint(...) end

---@param ... any
---@return any
function glm.aabb2d.contains(...) end

---@param ... any
---@return any
function glm.aabb2d.containsAABB(...) end

---@param ... any
---@return any
function glm.aabb2d.containsSegment(...) end

---@param ... any
---@return any
function glm.aabb2d.containsSphere(...) end

---@param ... any
---@return any
function glm.aabb2d.cornerPoint(...) end

---@param ... any
---@return any
function glm.aabb2d.diagonal(...) end

---@param ... any
---@return any
function glm.aabb2d.distance(...) end

---@param ... any
---@return any
function glm.aabb2d.distanceSphere(...) end

---@param ... any
---@return any
function glm.aabb2d.edge(...) end

---@param ... any
---@return any
function glm.aabb2d.enclose(...) end

---@param ... any
---@return any
function glm.aabb2d.encloseAABB(...) end

---@param ... any
---@return any
function glm.aabb2d.encloseSegment(...) end

---@param ... any
---@return any
function glm.aabb2d.encloseSphere(...) end

---@param ... any
---@return any
function glm.aabb2d.equal(...) end

---@param ... any
---@return any
function glm.aabb2d.extremePoint(...) end

---@param ... any
---@return any
function glm.aabb2d.fromCenterAndSize(...) end

---@param ... any
---@return any
function glm.aabb2d.grow(...) end

---@param ... any
---@return any
function glm.aabb2d.halfDiagonal(...) end

---@param ... any
---@return any
function glm.aabb2d.halfSize(...) end

---@param ... any
---@return any
function glm.aabb2d.intersectAABB(...) end

---@param ... any
---@return any
function glm.aabb2d.intersection(...) end

---@param ... any
---@return any
function glm.aabb2d.intersectLine(...) end

---@param ... any
---@return any
function glm.aabb2d.intersectRay(...) end

---@param ... any
---@return any
function glm.aabb2d.intersectsAABB(...) end

---@param ... any
---@return any
function glm.aabb2d.intersectSegment(...) end

---@param ... any
---@return any
function glm.aabb2d.intersectsLine(...) end

---@param ... any
---@return any
function glm.aabb2d.intersectsRay(...) end

---@param ... any
---@return any
function glm.aabb2d.intersectsSegment(...) end

---@param ... any
---@return any
function glm.aabb2d.isDegenerate(...) end

---@param ... any
---@return any
function glm.aabb2d.isfinite(...) end

---@param ... any
---@return any
function glm.aabb2d.isinf(...) end

---@param ... any
---@return any
function glm.aabb2d.isnan(...) end

---@param ... any
---@return any
function glm.aabb2d.new(...) end

---@param ... any
---@return any
function glm.aabb2d.notEqual(...) end

---@param ... any
---@return any
function glm.aabb2d.pointInside(...) end

---@param ... any
---@return any
function glm.aabb2d.projectToAxis(...) end

---@param ... any
---@return any
function glm.aabb2d.scale(...) end

---@param ... any
---@return any
function glm.aabb2d.size(...) end

---@param ... any
---@return any
function glm.aabb2d.volume(...) end

---Geometry helpers for circle shapes.
---@class glm.circle
glm.circle = {}

---@param ... any
---@return any
function glm.circle.area(...) end

---@param ... any
---@return any
function glm.circle.closestPoint(...) end

---@param ... any
---@return any
function glm.circle.contains(...) end

---@param ... any
---@return any
function glm.circle.containsAABB(...) end

---@param ... any
---@return any
function glm.circle.containsCircle(...) end

---@param ... any
---@return any
function glm.circle.containsSegment(...) end

---@param ... any
---@return any
function glm.circle.distance(...) end

---@param ... any
---@return any
function glm.circle.distanceAABB(...) end

---@param ... any
---@return any
function glm.circle.distanceLine(...) end

---@param ... any
---@return any
function glm.circle.distanceRay(...) end

---@param ... any
---@return any
function glm.circle.distanceSegment(...) end

---@param ... any
---@return any
function glm.circle.distanceSphere(...) end

---@param ... any
---@return any
function glm.circle.enclose(...) end

---@param ... any
---@return any
function glm.circle.encloseAABB(...) end

---@param ... any
---@return any
function glm.circle.encloseSegment(...) end

---@param ... any
---@return any
function glm.circle.encloseSphere(...) end

---@param ... any
---@return any
function glm.circle.equal(...) end

---@param ... any
---@return any
function glm.circle.extendRadiusToContain(...) end

---@param ... any
---@return any
function glm.circle.extendRadiusToContainCircle(...) end

---@param ... any
---@return any
function glm.circle.extremePoint(...) end

---@param ... any
---@return any
function glm.circle.intersectAABB(...) end

---@param ... any
---@return any
function glm.circle.intersectCircle(...) end

---@param ... any
---@return any
function glm.circle.intersectLine(...) end

---@param ... any
---@return any
function glm.circle.intersectPlane(...) end

---@param ... any
---@return any
function glm.circle.intersectRay(...) end

---@param ... any
---@return any
function glm.circle.intersectsAABB(...) end

---@param ... any
---@return any
function glm.circle.intersectsCircle(...) end

---@param ... any
---@return any
function glm.circle.intersectSegment(...) end

---@param ... any
---@return any
function glm.circle.intersectsLine(...) end

---@param ... any
---@return any
function glm.circle.intersectsPlane(...) end

---@param ... any
---@return any
function glm.circle.intersectsRay(...) end

---@param ... any
---@return any
function glm.circle.intersectsSegment(...) end

---@param ... any
---@return any
function glm.circle.isDegenerate(...) end

---@param ... any
---@return any
function glm.circle.isfinite(...) end

---@param ... any
---@return any
function glm.circle.isinf(...) end

---@param ... any
---@return any
function glm.circle.isnan(...) end

---@param ... any
---@return any
function glm.circle.maximalContainedAABB(...) end

---@param ... any
---@return any
function glm.circle.notEqual(...) end

---@param ... any
---@return any
function glm.circle.projectToAxis(...) end

---Geometry helpers for line shapes.
---@class glm.line
glm.line = {}

---@param ... any
---@return any
function glm.line.closest(...) end

---@param ... any
---@return any
function glm.line.closestLine(...) end

---@param ... any
---@return any
function glm.line.closestRay(...) end

---@param ... any
---@return any
function glm.line.closestSegment(...) end

---@param ... any
---@return any
function glm.line.closestTriangle(...) end

---@param ... any
---@return any
function glm.line.contains(...) end

---@param ... any
---@return any
function glm.line.containsRay(...) end

---@param ... any
---@return any
function glm.line.containsSegment(...) end

---@param ... any
---@return any
function glm.line.distance(...) end

---@param ... any
---@return any
function glm.line.distanceLine(...) end

---@param ... any
---@return any
function glm.line.distanceRay(...) end

---@param ... any
---@return any
function glm.line.distanceSegment(...) end

---@param ... any
---@return any
function glm.line.distanceSphere(...) end

---@param ... any
---@return any
function glm.line.equal(...) end

---@param ... any
---@return any
function glm.line.getPoint(...) end

---@param ... any
---@return any
function glm.line.intersectAABB(...) end

---@param ... any
---@return any
function glm.line.intersectPlane(...) end

---@param ... any
---@return any
function glm.line.intersectsAABB(...) end

---@param ... any
---@return any
function glm.line.intersectSphere(...) end

---@param ... any
---@return any
function glm.line.intersectsPlane(...) end

---@param ... any
---@return any
function glm.line.intersectsSphere(...) end

---@param ... any
---@return any
function glm.line.intersectsTriangle(...) end

---@param ... any
---@return any
function glm.line.isfinite(...) end

---@param ... any
---@return any
function glm.line.isinf(...) end

---@param ... any
---@return any
function glm.line.isnan(...) end

---@param ... any
---@return any
function glm.line.notEqual(...) end

---@param ... any
---@return any
function glm.line.projectToAxis(...) end

---@param ... any
---@return any
function glm.line.to_segment(...) end

---Geometry helpers for plane shapes.
---@class glm.plane
glm.plane = {}

---@param ... any
---@return any
function glm.plane.angle(...) end

---@param ... any
---@return any
function glm.plane.areOnSameSide(...) end

---@param ... any
---@return any
function glm.plane.clipLine(...) end

---@param ... any
---@return any
function glm.plane.clipSegment(...) end

---@param ... any
---@return any
function glm.plane.clipTriangle(...) end

---@param ... any
---@return any
function glm.plane.closestPointRay(...) end

---@param ... any
---@return any
function glm.plane.closestPointSegment(...) end

---@param ... any
---@return any
function glm.plane.contains(...) end

---@param ... any
---@return any
function glm.plane.containsLine(...) end

---@param ... any
---@return any
function glm.plane.containsRay(...) end

---@param ... any
---@return any
function glm.plane.containsSegment(...) end

---@param ... any
---@return any
function glm.plane.containsTriangle(...) end

---@param ... any
---@return any
function glm.plane.distance(...) end

---@param ... any
---@return any
function glm.plane.distanceSegment(...) end

---@param ... any
---@return any
function glm.plane.distanceSphere(...) end

---@param ... any
---@return any
function glm.plane.equal(...) end

---@param ... any
---@return any
function glm.plane.examineSide(...) end

---@param ... any
---@return any
function glm.plane.fromLine(...) end

---@param ... any
---@return any
function glm.plane.fromLineSegment(...) end

---@param ... any
---@return any
function glm.plane.fromPointNormal(...) end

---@param ... any
---@return any
function glm.plane.fromPoints(...) end

---@param ... any
---@return any
function glm.plane.fromRay(...) end

---@param ... any
---@return any
function glm.plane.intersectsAABB(...) end

---@param ... any
---@return any
function glm.plane.intersectsLine(...) end

---@param ... any
---@return any
function glm.plane.intersectsPlane(...) end

---@param ... any
---@return any
function glm.plane.intersectsRay(...) end

---@param ... any
---@return any
function glm.plane.intersectsSegment(...) end

---@param ... any
---@return any
function glm.plane.intersectsSphere(...) end

---@param ... any
---@return any
function glm.plane.intersectsTriangle(...) end

---@param ... any
---@return any
function glm.plane.isDegenerate(...) end

---@param ... any
---@return any
function glm.plane.isInPositiveDirection(...) end

---@param ... any
---@return any
function glm.plane.isOnPositiveSide(...) end

---@param ... any
---@return any
function glm.plane.isParallel(...) end

---@param ... any
---@return any
function glm.plane.mirror(...) end

---@param ... any
---@return any
function glm.plane.mirrorMatrix(...) end

---@param ... any
---@return any
function glm.plane.notEqual(...) end

---@param ... any
---@return any
function glm.plane.orthoProjection(...) end

---@param ... any
---@return any
function glm.plane.passesThroughOrigin(...) end

---@param ... any
---@return any
function glm.plane.point(...) end

---@param ... any
---@return any
function glm.plane.pointOnPlane(...) end

---@param ... any
---@return any
function glm.plane.project(...) end

---@param ... any
---@return any
function glm.plane.projectLine(...) end

---@param ... any
---@return any
function glm.plane.projectRay(...) end

---@param ... any
---@return any
function glm.plane.projectSegment(...) end

---@param ... any
---@return any
function glm.plane.projectToNegativeHalf(...) end

---@param ... any
---@return any
function glm.plane.projectToPositiveHalf(...) end

---@param ... any
---@return any
function glm.plane.projectTriangle(...) end

---@param ... any
---@return any
function glm.plane.refract(...) end

---@param ... any
---@return any
function glm.plane.reverseNormal(...) end

---@param ... any
---@return any
function glm.plane.signedDistance(...) end

---@param ... any
---@return any
function glm.plane.signedDistanceAABB(...) end

---@param ... any
---@return any
function glm.plane.signedDistanceLine(...) end

---@param ... any
---@return any
function glm.plane.signedDistanceRay(...) end

---@param ... any
---@return any
function glm.plane.signedDistanceSegment(...) end

---@param ... any
---@return any
function glm.plane.signedDistanceSphere(...) end

---@param ... any
---@return any
function glm.plane.signedDistanceTriangle(...) end

---Geometry helpers for polygon shapes.
---@class glm.polygon
glm.polygon = {}

---Surface area of the polygon.
---@param self glm.polygon
---@return number
function glm.polygon.area(self) end

---@param ... any
---@return any
function glm.polygon.basisU(...) end

---@param ... any
---@return any
function glm.polygon.basisV(...) end

---Centre of mass of the polygon.
---@param self glm.polygon
---@return vector3
function glm.polygon.centroid(self) end

---Whether `point` lies within the polygon, allowing `thickness` along its normal.
---@param self glm.polygon
---@param point vector3
---@param thickness? number
---@return boolean
function glm.polygon.contains(self, point, thickness) end

---@param ... any
---@return any
function glm.polygon.containsAbove(...) end

---@param ... any
---@return any
function glm.polygon.containsBelow(...) end

---@param ... any
---@return any
function glm.polygon.containsPolygon(...) end

---@param ... any
---@return any
function glm.polygon.containsSegment(...) end

---@param ... any
---@return any
function glm.polygon.containsSegment2D(...) end

---@param ... any
---@return any
function glm.polygon.containsTriangle(...) end

---@param ... any
---@return any
function glm.polygon.diagonal(...) end

---@param ... any
---@return any
function glm.polygon.diagonalExists(...) end

---@param ... any
---@return any
function glm.polygon.edge(...) end

---@param ... any
---@return any
function glm.polygon.edge2d(...) end

---@param ... any
---@return any
function glm.polygon.edgeNormal(...) end

---@param ... any
---@return any
function glm.polygon.edgePlane(...) end

---@param ... any
---@return any
function glm.polygon.extremePoint(...) end

---@param ... any
---@return any
function glm.polygon.intersectsLine(...) end

---@param ... any
---@return any
function glm.polygon.intersectsPlane(...) end

---@param ... any
---@return any
function glm.polygon.intersectsRay(...) end

---@param ... any
---@return any
function glm.polygon.intersectsSegment(...) end

---@param ... any
---@return any
function glm.polygon.intersectsSegment2D(...) end

---Whether the polygon is convex.
---@param self glm.polygon
---@return boolean
function glm.polygon.isConvex(self) end

---@param ... any
---@return any
function glm.polygon.isDegenerate(...) end

---@param ... any
---@return any
function glm.polygon.isfinite(...) end

---@param ... any
---@return any
function glm.polygon.isNull(...) end

---Whether all points lie in one plane.
---@param self glm.polygon
---@return boolean
function glm.polygon.isPlanar(self) end

---@param ... any
---@return any
function glm.polygon.isSimple(...) end

---@param ... any
---@return any
function glm.polygon.mapFrom2D(...) end

---@param ... any
---@return any
function glm.polygon.mapTo2D(...) end

---@param ... any
---@return any
function glm.polygon.minimalEnclosingAABB(...) end

---Builds a polygon from its corner points.
---@param points vector3[]
---@return glm.polygon
function glm.polygon.new(points) end

---@param ... any
---@return any
function glm.polygon.normalCCW(...) end

---@param ... any
---@return any
function glm.polygon.normalCW(...) end

---Summed length of the edges.
---@param self glm.polygon
---@return number
function glm.polygon.perimeter(self) end

---@param ... any
---@return any
function glm.polygon.planeCCW(...) end

---@param ... any
---@return any
function glm.polygon.planeCW(...) end

---@param ... any
---@return any
function glm.polygon.pointOnEdge(...) end

---@param ... any
---@return any
function glm.polygon.projectToAxis(...) end

---Geometry helpers for ray shapes.
---@class glm.ray
glm.ray = {}

---@param ... any
---@return any
function glm.ray.closest(...) end

---@param ... any
---@return any
function glm.ray.closestLine(...) end

---@param ... any
---@return any
function glm.ray.closestRay(...) end

---@param ... any
---@return any
function glm.ray.closestSegment(...) end

---@param ... any
---@return any
function glm.ray.contains(...) end

---@param ... any
---@return any
function glm.ray.containsSegment(...) end

---@param ... any
---@return any
function glm.ray.distance(...) end

---@param ... any
---@return any
function glm.ray.distanceLine(...) end

---@param ... any
---@return any
function glm.ray.distanceRay(...) end

---@param ... any
---@return any
function glm.ray.distanceSegment(...) end

---@param ... any
---@return any
function glm.ray.distanceSphere(...) end

---@param ... any
---@return any
function glm.ray.equal(...) end

---@param ... any
---@return any
function glm.ray.getPoint(...) end

---@param ... any
---@return any
function glm.ray.intersectAABB(...) end

---@param ... any
---@return any
function glm.ray.intersectPlane(...) end

---@param ... any
---@return any
function glm.ray.intersectsAABB(...) end

---@param ... any
---@return any
function glm.ray.intersectSphere(...) end

---@param ... any
---@return any
function glm.ray.intersectsSphere(...) end

---@param ... any
---@return any
function glm.ray.intersectsTriangle(...) end

---@param ... any
---@return any
function glm.ray.isfinite(...) end

---@param ... any
---@return any
function glm.ray.isinf(...) end

---@param ... any
---@return any
function glm.ray.isnan(...) end

---@param ... any
---@return any
function glm.ray.notEqual(...) end

---@param ... any
---@return any
function glm.ray.projectToAxis(...) end

---Geometry helpers for segment shapes.
---@class glm.segment
glm.segment = {}

---@param ... any
---@return any
function glm.segment.centerPoint(...) end

---@param ... any
---@return any
function glm.segment.centroid(...) end

---@param ... any
---@return any
function glm.segment.closestLine(...) end

---@param ... any
---@return any
function glm.segment.closestPoint(...) end

---@param ... any
---@return any
function glm.segment.closestRay(...) end

---@param ... any
---@return any
function glm.segment.closestSegment(...) end

---@param ... any
---@return any
function glm.segment.closestTriangle(...) end

---@param ... any
---@return any
function glm.segment.containsPoint(...) end

---@param ... any
---@return any
function glm.segment.containsSegment(...) end

---@param ... any
---@return any
function glm.segment.dir(...) end

---@param ... any
---@return any
function glm.segment.distance(...) end

---@param ... any
---@return any
function glm.segment.distance2(...) end

---@param ... any
---@return any
function glm.segment.distanceLine(...) end

---@param ... any
---@return any
function glm.segment.distancePlane(...) end

---@param ... any
---@return any
function glm.segment.distanceRay(...) end

---@param ... any
---@return any
function glm.segment.distanceSegment(...) end

---@param ... any
---@return any
function glm.segment.distanceSegment2(...) end

---@param ... any
---@return any
function glm.segment.equal(...) end

---@param ... any
---@return any
function glm.segment.extremePoint(...) end

---@param ... any
---@return any
function glm.segment.getPoint(...) end

---@param ... any
---@return any
function glm.segment.intersectsAABB(...) end

---@param ... any
---@return any
function glm.segment.intersectsPlane(...) end

---@param ... any
---@return any
function glm.segment.intersectsSegment(...) end

---@param ... any
---@return any
function glm.segment.intersectsSphere(...) end

---@param ... any
---@return any
function glm.segment.intersectsTriangle(...) end

---@param ... any
---@return any
function glm.segment.isfinite(...) end

---@param ... any
---@return any
function glm.segment.length(...) end

---@param ... any
---@return any
function glm.segment.length2(...) end

---@param ... any
---@return any
function glm.segment.notEqual(...) end

---@param ... any
---@return any
function glm.segment.reverse(...) end

---Geometry helpers for segment2d shapes.
---@class glm.segment2d
glm.segment2d = {}

---@param ... any
---@return any
function glm.segment2d.centerPoint(...) end

---@param ... any
---@return any
function glm.segment2d.centroid(...) end

---@param ... any
---@return any
function glm.segment2d.closestLine(...) end

---@param ... any
---@return any
function glm.segment2d.closestPoint(...) end

---@param ... any
---@return any
function glm.segment2d.closestRay(...) end

---@param ... any
---@return any
function glm.segment2d.closestSegment(...) end

---@param ... any
---@return any
function glm.segment2d.containsPoint(...) end

---@param ... any
---@return any
function glm.segment2d.containsSegment(...) end

---@param ... any
---@return any
function glm.segment2d.dir(...) end

---@param ... any
---@return any
function glm.segment2d.distance(...) end

---@param ... any
---@return any
function glm.segment2d.distance2(...) end

---@param ... any
---@return any
function glm.segment2d.distanceLine(...) end

---@param ... any
---@return any
function glm.segment2d.distancePlane(...) end

---@param ... any
---@return any
function glm.segment2d.distanceRay(...) end

---@param ... any
---@return any
function glm.segment2d.distanceSegment(...) end

---@param ... any
---@return any
function glm.segment2d.distanceSegment2(...) end

---@param ... any
---@return any
function glm.segment2d.equal(...) end

---@param ... any
---@return any
function glm.segment2d.extremePoint(...) end

---@param ... any
---@return any
function glm.segment2d.getPoint(...) end

---@param ... any
---@return any
function glm.segment2d.intersectsAABB(...) end

---@param ... any
---@return any
function glm.segment2d.intersectsSegment(...) end

---@param ... any
---@return any
function glm.segment2d.isfinite(...) end

---@param ... any
---@return any
function glm.segment2d.length(...) end

---@param ... any
---@return any
function glm.segment2d.length2(...) end

---@param ... any
---@return any
function glm.segment2d.notEqual(...) end

---@param ... any
---@return any
function glm.segment2d.reverse(...) end

---Geometry helpers for sphere shapes.
---@class glm.sphere
glm.sphere = {}

---@param ... any
---@return any
function glm.sphere.closestPoint(...) end

---@param ... any
---@return any
function glm.sphere.contains(...) end

---@param ... any
---@return any
function glm.sphere.containsAABB(...) end

---@param ... any
---@return any
function glm.sphere.containsSegment(...) end

---@param ... any
---@return any
function glm.sphere.containsSphere(...) end

---@param ... any
---@return any
function glm.sphere.containsTriangle(...) end

---@param ... any
---@return any
function glm.sphere.distance(...) end

---@param ... any
---@return any
function glm.sphere.distanceAABB(...) end

---@param ... any
---@return any
function glm.sphere.distanceLine(...) end

---@param ... any
---@return any
function glm.sphere.distanceRay(...) end

---@param ... any
---@return any
function glm.sphere.distanceSegment(...) end

---@param ... any
---@return any
function glm.sphere.distanceSphere(...) end

---@param ... any
---@return any
function glm.sphere.distanceTriangle(...) end

---@param ... any
---@return any
function glm.sphere.enclose(...) end

---@param ... any
---@return any
function glm.sphere.encloseAABB(...) end

---@param ... any
---@return any
function glm.sphere.encloseSegment(...) end

---@param ... any
---@return any
function glm.sphere.encloseSphere(...) end

---@param ... any
---@return any
function glm.sphere.encloseTriangle(...) end

---@param ... any
---@return any
function glm.sphere.equal(...) end

---@param ... any
---@return any
function glm.sphere.extendRadiusToContain(...) end

---@param ... any
---@return any
function glm.sphere.extendRadiusToContainSphere(...) end

---@param ... any
---@return any
function glm.sphere.extremePoint(...) end

---@param ... any
---@return any
function glm.sphere.fitThroughPoints(...) end

---@param ... any
---@return any
function glm.sphere.intersectAABB(...) end

---@param ... any
---@return any
function glm.sphere.intersectLine(...) end

---@param ... any
---@return any
function glm.sphere.intersectPlane(...) end

---@param ... any
---@return any
function glm.sphere.intersectRay(...) end

---@param ... any
---@return any
function glm.sphere.intersectsAABB(...) end

---@param ... any
---@return any
function glm.sphere.intersectSegment(...) end

---@param ... any
---@return any
function glm.sphere.intersectsLine(...) end

---@param ... any
---@return any
function glm.sphere.intersectSphere(...) end

---@param ... any
---@return any
function glm.sphere.intersectsPlane(...) end

---@param ... any
---@return any
function glm.sphere.intersectsRay(...) end

---@param ... any
---@return any
function glm.sphere.intersectsSegment(...) end

---@param ... any
---@return any
function glm.sphere.intersectsSphere(...) end

---@param ... any
---@return any
function glm.sphere.intersectsTriangle(...) end

---@param ... any
---@return any
function glm.sphere.isDegenerate(...) end

---@param ... any
---@return any
function glm.sphere.isfinite(...) end

---@param ... any
---@return any
function glm.sphere.isinf(...) end

---@param ... any
---@return any
function glm.sphere.isnan(...) end

---@param ... any
---@return any
function glm.sphere.maximalContainedAABB(...) end

---@param ... any
---@return any
function glm.sphere.notEqual(...) end

---@param ... any
---@return any
function glm.sphere.optimalEnclosingSphere(...) end

---@param ... any
---@return any
function glm.sphere.projectToAxis(...) end

---@param ... any
---@return any
function glm.sphere.surfaceArea(...) end

---@param ... any
---@return any
function glm.sphere.volume(...) end

---Geometry helpers for triangle shapes.
---@class glm.triangle
glm.triangle = {}

---@param ... any
---@return any
function glm.triangle.area(...) end

---@param ... any
---@return any
function glm.triangle.boundingAABB(...) end

---@param ... any
---@return any
function glm.triangle.centroid(...) end

---@param ... any
---@return any
function glm.triangle.closestLine(...) end

---@param ... any
---@return any
function glm.triangle.closestPoint(...) end

---@param ... any
---@return any
function glm.triangle.closestSegment(...) end

---@param ... any
---@return any
function glm.triangle.contains(...) end

---@param ... any
---@return any
function glm.triangle.containsSegment(...) end

---@param ... any
---@return any
function glm.triangle.containsTriangle(...) end

---@param ... any
---@return any
function glm.triangle.cornerPoint(...) end

---@param ... any
---@return any
function glm.triangle.distance(...) end

---@param ... any
---@return any
function glm.triangle.distanceSphere(...) end

---@param ... any
---@return any
function glm.triangle.edge(...) end

---@param ... any
---@return any
function glm.triangle.equal(...) end

---@param ... any
---@return any
function glm.triangle.extremePoint(...) end

---@param ... any
---@return any
function glm.triangle.inside_triangle(...) end

---@param ... any
---@return any
function glm.triangle.intersectsAABB(...) end

---@param ... any
---@return any
function glm.triangle.intersectsLine(...) end

---@param ... any
---@return any
function glm.triangle.intersectsPlane(...) end

---@param ... any
---@return any
function glm.triangle.intersectsRay(...) end

---@param ... any
---@return any
function glm.triangle.intersectsSegment(...) end

---@param ... any
---@return any
function glm.triangle.intersectsSphere(...) end

---@param ... any
---@return any
function glm.triangle.isDegenerate(...) end

---@param ... any
---@return any
function glm.triangle.isfinite(...) end

---@param ... any
---@return any
function glm.triangle.isinf(...) end

---@param ... any
---@return any
function glm.triangle.isnan(...) end

---@param ... any
---@return any
function glm.triangle.normalCCW(...) end

---@param ... any
---@return any
function glm.triangle.normalCW(...) end

---@param ... any
---@return any
function glm.triangle.notEqual(...) end

---@param ... any
---@return any
function glm.triangle.perimeter(...) end

---@param ... any
---@return any
function glm.triangle.planeCCW(...) end

---@param ... any
---@return any
function glm.triangle.planeCW(...) end

---@param ... any
---@return any
function glm.triangle.pointuv(...) end

---@param ... any
---@return any
function glm.triangle.pointuvw(...) end

---@param ... any
---@return any
function glm.triangle.signedArea(...) end

---@param ... any
---@return any
function glm.triangle.unnormalizedNormalCCW(...) end

---@param ... any
---@return any
function glm.triangle.unnormalizedNormalCW(...) end

---@param ... any
---@return any
function glm.triangle.uv(...) end

---@param ... any
---@return any
function glm.triangle.uvw(...) end
